const menuList = [
  {
    title:"首页",
    key:"/admin/home"
  },
  {
    title:'UI',
    key:"/admin/ui",
    children:[
      {
        title:"按钮",
        key:"/admin/ui/buttons",
      },
      {
        title:"弹框",
        key:"/admin/ui/modals",
      },
      {
        title:"Loading",
        key:"/admin/ui/loading"
      },
      {
        title:"通知提醒",
        key:"/admin/ui/notify"
      },
      {
        title:"全局Message",
        key:"/admin/ui/message"
      },
      {
        title:"Tab标签",
        key:"/admin/ui/label"
      },
      {
        title:"图片画廊",
        key:"/admin/ui/pic"
      },
      {
        title:"轮播图",
        key:"/admin/ui/swiper"
      }
    ]
  },
  {
    title:"表格",
    key:"/admin/form",
    children:[
      {
        title:"登录",
        key:"/admin/from/login"
      },
      {
        title:"注册",
        key:"/admin/form/reg"
      }
    ]
  },
  {
    title:"副文本",
    key:"/admin/text"
  },
  {
    title:"表格",
    key:"/admin/table"
  }
]

export default menuList;